# Configurações de Conexão com o Banco de Dados (Supabase / PostgreSQL)

# URL de conexão JDBC para o Pooler do Supabase (Porta 5432 - Session Mode, IPv4)
db.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require

# Usuário do banco de dados do Supabase
db.user=postgres.fbgqjbkwnfwsvgdpskmm

# Senha do banco de dados
db.password=lPK8pBsNYNZVQoLF
