create table if not exists public.agenda_lembretes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    data date not null,
    texto text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, data)
);

alter table public.agenda_lembretes enable row level security;

drop policy if exists "Usuarios podem ver seus lembretes" on public.agenda_lembretes;
create policy "Usuarios podem ver seus lembretes"
on public.agenda_lembretes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Usuarios podem criar seus lembretes" on public.agenda_lembretes;
create policy "Usuarios podem criar seus lembretes"
on public.agenda_lembretes
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Usuarios podem editar seus lembretes" on public.agenda_lembretes;
create policy "Usuarios podem editar seus lembretes"
on public.agenda_lembretes
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Usuarios podem apagar seus lembretes" on public.agenda_lembretes;
create policy "Usuarios podem apagar seus lembretes"
on public.agenda_lembretes
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_agenda_lembretes_updated_at on public.agenda_lembretes;

create trigger set_agenda_lembretes_updated_at
before update on public.agenda_lembretes
for each row
execute function public.set_updated_at();
